version: '3.8'

services:
  app:
    image: cotizate-app:latest
    container_name: cotizate-app-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      API_VERSION: ${API_VERSION:-v1}
      CORS_ORIGIN: ${CORS_ORIGIN}
    networks:
      - cotizate-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  cotizate-network:
    driver: bridge